channels:
    - pytorch
    - conda-forge
    - defaults
name:
    autophago-train-env
dependencies:
    - cudatoolkit >=10.2
    - h5py
    - imageio
    - inferno
    - napari
    - neurofire
    - pytorch
    - scikit-image
    - torchvision
    - tqdm
    - vigra
    - z5py
    # try installing apex at some point
    # https://anaconda.org/conda-forge/nvidia-apex
    # - nvidia-apex
